### PR TITLE
pls review

### PR DESCRIPTION
**Pull request by rkyzk**

### CODE REVIEW

**Comment by rkyzk** [comment]
wait PL

**Comment by rkyzk** [comment]
Please don't approve, i had to change setting, but forgot to put it back. i will do this over.  sorry about this.

**Comment by rkyzk** [comment]
these changes should be good in fact.  please review.  i'd appreciate it.

**Review by CamCove-Crichton — COMMENTED** [review]
Looking at this, most of it looks great, but my only thought is it seems the views in the home app are being removed, but I do not seem to seem them in the budget views, but I do see some docstring there, so before I approve, and potentially lose those views in the home app views.py, I just want to make sure they are being moved over to the budget app views.py file?

**Comment by rkyzk** [comment]
excuse me the comment was not write, I moved the functions to functions.py in budget.  all I intended to push is there.  please approve this one

**Review by CamCove-Crichton — APPROVED** [review]
Okay I see what you mean, sorry that was my mistake

**Comment by rkyzk** [comment]
I decided to redo this from another branch

**Pull request closed without merging**
